In [1]:
import requests
from io import StringIO
import numpy as np 
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day20-univariate-analysis/train.csv"
req=requests.get(url).text
data=StringIO(req)
df=pd.read_csv(data)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],inplace=True)

In [4]:
df.sample(5)

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
880         1       2  female  25.0      0      1   26.0000        S
484         1       1    male  25.0      1      0   91.0792        C
777         1       3  female   5.0      0      0   12.4750        S
242         0       2    male  29.0      0      0   10.5000        S
498         0       1  female  25.0      1      2  151.5500        S

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop("Survived",axis=1),df.Survived,test_size=0.32,random_state=0)

In [6]:
X_train

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
532       3    male  17.0      1      1   7.2292        C
485       3  female   NaN      3      1  25.4667        S
695       2    male  52.0      0      0  13.5000        S
475       1    male   NaN      0      0  52.0000        S
17        2    male   NaN      0      0  13.0000        S
..      ...     ...   ...    ...    ...      ...      ...
835       1  female  39.0      1      1  83.1583        C
192       3  female  19.0      1      0   7.8542        S
629       3    male   NaN      0      0   7.7333        Q
559       3  female  36.0      1      0  17.4000        S
684       2    male  60.0      1      1  39.0000        S

[605 rows x 7 columns]

In [7]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.model_selection import cross_val_score,GridSearchCV

from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer

In [8]:
trf1=ColumnTransformer(transformers=[
    ("trsdf",SimpleImputer(strategy="mean"),[2]),
    ("ldjkal",SimpleImputer(strategy="most_frequent"),[6])
  
    
],remainder="passthrough")

In [15]:
trf2=ColumnTransformer(transformers=[  ("ssdjk",OneHotEncoder(sparse_output=False,drop="first"),[1,6])],remainder="passthrough")
trf3=ColumnTransformer(transformers=[  ("ssdjkfg",MinMaxScaler(),slice(0,9))],remainder="passthrough")

In [16]:
trf4=DecisionTreeClassifier()

In [17]:
from sklearn import set_config
set_config(display="diagram")

In [18]:
from sklearn.pipeline import Pipeline

In [19]:
pipe=Pipeline([("trf1",trf1),("trf2",trf2),("trf3",trf3),("trf4",trf4)])

In [20]:
pipe.fit(X_train,y_train)

ValueError: could not convert string to float: 'male'